name: EconomyPShop
version: "2.0.2"
author: onebone
main: onebone\economypshop\EconomyPShop

api:
- 1.0.0
- 1.1.0
- 1.2.0
- 1.2.1
- 1.3.0
- 1.3.1
- 1.4.0
- 1.4.1
- 1.12.0
- 1.13.0
- 2.0.0

permissions:
 economypshop.*:
  description: Allows all permissions to the player
  children:
   economypshop.shop.*:
    description: Allows player all permissions related to shop
    children:
     economypshop.shop.create:
      description: Allows player to create shop
      default: true
     economypshop.shop.buy:
      description: Allows player to buy items from shop
      default: true
     economypshop.shop.destroy.others:
      description: Allows player to destroy others' shop
