# Language which plugin will use
language: en

# Land is unloaded if not access by player for a long time.
# This is a configuration for setting the period to check this task.
# DO NOT TOUCH THIS if you don't know what you are doing.
# unit: ticks
land-unload-task-period: 200
# unit: seconds
land-unload-after: 10
