name: EconomyShop
version: "2.0.1"
api:
- 1.3.0
- 1.3.1
- 1.4.0
- 1.4.1
main: onebone\economyshop\EconomyShop
author: onebone
depend: [EconomyAPI]

permissions:
 economyshop.*:
  description: Allows all functions in EconomyShop
  default: op
  children:
   economyshop.shop.*:
    description: Allows all functions about shops
    default: op
    children:
     economyshop.shop.create:
      description: Allows player to create shop
      default: op
     economyshop.shop.remove:
      description: Allows player to remove shop
      default: op